//Auth && user
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE'

//Lists
export const FETCH_HOME_DATA = 'FETCH_HOME_DATA'
export const FETCH_SERIES_BY_CATEGORIES = 'FETCH_SERIES_BY_CATEGORIES'
export const FETCH_SERIES_BY_CATEGORIES_STARPLAY = 'FETCH_SERIES_BY_CATEGORIES_STARPLAY'
export const FETCH_FEATURED_SERIES = 'FETCH_FEATURED_SERIES'
export const FETCH_FEATURED_SERIES_STAR = 'FETCH_FEATURED_SERIES_STAR'
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES'
export const FETCH_CATEGORY_SERIES = 'FETCH_CATEGORY_SERIES'
export const FETCH_TRENDING_SERIES = 'FETCH_TRENDING_SERIES'
export const FETCH_TRENDING_SERIES_STAR = 'FETCH_TRENDING_SERIES_STAR'
export const FETCH_WATCH_HISTORY = 'FETCH_WATCH_HISTORY'
export const UPDATE_WATCH_HISTORY = 'UPDATE_WATCH_HISTORY'

//Player
export const UPDATE_TRACK = 'UPDATE_CURRENT_TRACK'
export const UPDATE_SERIES = 'UPDATE_CURRENT_SERIES'
export const UPDATE_TRACKS_LIST = 'UPDATE_TRACKS_LIST'
export const UPDATE_CURRENT_TRACK_INDEX = 'UPDATE_CURRENT_TRACK_INDEX'
export const UPDATE_CURRENT_NETWORK_STATE = 'update_current_network_state'

//Error
export const ERROR = 'error';
export const CLEAR_ERROR = 'clear_error';
export const INFO = 'info';
export const CLEAR_INFO = 'clear_info';

//Billing
export const GET_SUB_PLANS = 'GET_SUB_PLANS';
export const GET_USER_SUB_STATUS = 'GET_USER_SUB_STATUS';
export const UPDATE_WATCHED_LOCALLY = 'UPDATE_WATCHED_LOCALLY';
export const UPDATE_WATCHED_SECONDS_LOCALLY = 'UPDATE_WATCHED_SECONDS_LOCALLY';

//Downloads
export const UPDATE_ACTIVE_DOWNLOADS = 'UPDATE_ACTIVE_DOWNLOADS';

//app
export const FETCH_VERSIONS = 'FETCH_VERSIONS';
export const RESET = 'reset';
